name: Docker Image CI

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]


jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: deps
      run: |
        npm i -g next
        npm install
          
    - name: Build the Docker image
      run: |
        docker build . --file Dockerfile --tag ffr03/hello-world:latest

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Push to Docker Hub 
      run: |
        docker push ffr03/hello-world:latest


  dev:
    runs-on: ubuntu-latest
    needs:
      - build
    steps:
    - uses: actions/checkout@v3
    - name: Create k8s Kind Cluster
      uses: helm/kind-action@v1.4.0

    - name: Test k8s Kind Cluster
      run: |
        kubectl cluster-info
        kubectl get nodes

    - name: deploy app
      run: |
        kubectl apply -f hello.yml

  test:
    runs-on: ubuntu-latest
    needs:
      - dev

    steps:
      - uses: actions/checkout@v3
      - name: Create k8s Kind Cluster
        uses: helm/kind-action@v1.4.0

      - name: Test k8s Kind Cluster
        run: |
          kubectl cluster-info
          kubectl get nodes

      - name: deploy app
        run: |
          kubectl apply -f hello.yml

  prod:
    runs-on: ubuntu-latest
    needs:
      - test

    steps:
      - uses: actions/checkout@v3
      - name: Create k8s Kind Cluster
        uses: helm/kind-action@v1.4.0

      - name: Test k8s Kind Cluster
        run: |
          kubectl cluster-info
          kubectl get nodes

      - name: deploy app
        run: |
          kubectl apply -f hello.yml