name: Docker Image CI/CD

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]


jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: deps
      run: |
        npm i -g next
        npm install
          
    - name: Build the Docker image
      run: |
        docker build . --file Dockerfile --tag ffr03/hello-world:latest

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Push to Docker Hub 
      run: |
        docker push ffr03/hello-world:latest

    - name: Helm tool installer
      uses: Azure/setup-helm@v3

    - name: deploy monitoring
      run: |
        helm repo add prometheus https://prometheus-community.github.io/helm-charts
        helm repo update
        helm install --repo https://prometheus-community.github.io/helm-charts prometheus-operator-crds prometheus-operator-crds --atomic 
        helm install --repo https://prometheus-community.github.io/helm-charts prometheus kube-prometheus-stack --atomic  -f values.yml
        helm install --repo https://prometheus-community.github.io/helm-charts prometheus-node-exporter  prometheus-node-exporter --atomic 


  dev:
    runs-on: ubuntu-latest
    needs:
      - build
    steps:
    - uses: actions/checkout@v3
    - name: Create k8s Kind Cluster
      uses: helm/kind-action@v1.4.0

    - name: Test k8s Kind Cluster
      run: |
        kubectl cluster-info
        kubectl get nodes

    - name: deploy app
      run: |
        kubectl apply -f hello.yml

    - name: Helm tool installer
      uses: Azure/setup-helm@v3

    - name: deploy monitoring
      run: |
        helm repo add prometheus https://prometheus-community.github.io/helm-charts
        helm repo update
        helm install --repo https://prometheus-community.github.io/helm-charts prometheus-operator-crds prometheus-operator-crds --atomic 
        helm install --repo https://prometheus-community.github.io/helm-charts prometheus kube-prometheus-stack --atomic  -f values.yml
        helm install --repo https://prometheus-community.github.io/helm-charts prometheus-node-exporter  prometheus-node-exporter --atomic 



  test:
    runs-on: ubuntu-latest
    needs:
      - dev

    steps:
      - uses: actions/checkout@v3
      - name: Create k8s Kind Cluster
        uses: helm/kind-action@v1.4.0

      - name: Test k8s Kind Cluster
        run: |
          kubectl cluster-info
          kubectl get nodes

      - name: deploy app
        run: |
          kubectl apply -f hello.yml

      - name: deploy monitoring
        run: |
          helm repo add prometheus https://prometheus-community.github.io/helm-charts
          helm repo update
          helm install --repo https://prometheus-community.github.io/helm-charts prometheus-operator-crds prometheus-operator-crds --atomic 
          helm install --repo https://prometheus-community.github.io/helm-charts prometheus kube-prometheus-stack --atomic  -f values.yml
          helm install --repo https://prometheus-community.github.io/helm-charts prometheus-node-exporter  prometheus-node-exporter --atomic 



  prod:
    runs-on: ubuntu-latest
    needs:
      - test

    steps:
      - uses: actions/checkout@v3
      - name: Create k8s Kind Cluster
        uses: helm/kind-action@v1.4.0

      - name: Test k8s Kind Cluster
        run: |
          kubectl cluster-info
          kubectl get nodes

      - name: deploy app
        run: |
          kubectl apply -f hello.yml
          
      - name: deploy monitoring
        run: |
          helm repo add prometheus https://prometheus-community.github.io/helm-charts
          helm repo update
          helm install --repo https://prometheus-community.github.io/helm-charts prometheus-operator-crds prometheus-operator-crds --atomic 
          helm install --repo https://prometheus-community.github.io/helm-charts prometheus kube-prometheus-stack --atomic  -f values.yml
          helm install --repo https://prometheus-community.github.io/helm-charts prometheus-node-exporter  prometheus-node-exporter --atomic 

