name: Docker Image CI

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: deps
      run: |
        npm i -g next
        npm install
          
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ffr03/hello-world:latest
