name: Docker Image CI/CD

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: deps
      run: |
        npm i -g next
        npm install
          
    - name: Build the Docker image
      run: |
        docker build . --file Dockerfile --tag ffr03/hello-world:latest
        docker build . --file Dockerfile --tag ffr03//hello-world:${{ github.sha }}

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Push
      run: |
        docker push ffr03/hello-world:${{ github.sha }}
        docker build . -t ffr03/hello-world:latest