name: Docker Image CI/CD

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]


jobs:

  cicd:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: deps
      run: |
        npm i -g next
        npm install
          
    - name: Build the Docker image
      run: |
        docker build . --file Dockerfile --tag ffr03/hello-world:latest

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Push to Docker Hub 
      run: |
        docker push ffr03/hello-world:latest

    - name: Push to Docker Hub
      run: |
        docker push ffr03/hello-world:latest

    - name: Create k8s Kind Cluster
      uses: helm/kind-action@v1.4.0

    - name: Test k8s Kind Cluster
      run: |
        kubectl cluster-info
        kubectl get nodes

    - name: Test k8s Kind Cluster
      run: |
        kubectl apply -f hello.yml
